version: '3.9'

services:
  postgres:
    container_name: db-nestjs-test
    image: postgres
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=strongpassword'
    ports:
      - '5431:5432'
